# Generated by Django 5.2.6 on 2025-09-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='lojas_fotos/', verbose_name='Foto da Loja'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loja',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loja',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
