# Generated by Django 5.2.6 on 2025-10-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_loja_foto_alter_loja_endereco_alter_loja_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='loja/fotos/', verbose_name='Foto da Loja'),
        ),
    ]
