# Generated by Django 5.2.6 on 2025-10-05 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_loja_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='horario_funcionamento',
        ),
        migrations.AddField(
            model_name='loja',
            name='horario_abertura',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='loja',
            name='horario_fechamento',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='loja',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
