# Generated by Django 5.2.6 on 2025-10-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_remove_loja_horario_funcionamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='atendimento_emergencia',
            field=models.BooleanField(default=False, verbose_name='Atende Emergências (24h)'),
        ),
    ]
