# Generated by Django 5.2.6 on 2025-10-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_loja_atendimento_emergencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='foto',
        ),
        migrations.AddField(
            model_name='loja',
            name='descricao',
            field=models.TextField(blank=True, help_text='Fale um pouco sobre a loja, seus serviços e diferenciais.', null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='loja',
            name='foto_adicional_1',
            field=models.ImageField(blank=True, null=True, upload_to='loja/fotos/', verbose_name='Foto Adicional 1'),
        ),
        migrations.AddField(
            model_name='loja',
            name='foto_adicional_2',
            field=models.ImageField(blank=True, null=True, upload_to='loja/fotos/', verbose_name='Foto Adicional 2'),
        ),
        migrations.AddField(
            model_name='loja',
            name='foto_destaque',
            field=models.ImageField(blank=True, null=True, upload_to='loja/fotos/', verbose_name='Foto de Destaque'),
        ),
    ]
