# Generated by Django 5.2.6 on 2025-10-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_remove_loja_foto_loja_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='foto_adicional_1',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='foto_adicional_2',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='foto_destaque',
        ),
        migrations.AddField(
            model_name='loja',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='loja/fotos/', verbose_name='Foto da Loja'),
        ),
    ]
