# Generated by Django 5.2.6 on 2025-10-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_remove_loja_foto_adicional_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Use imagens com proporção de 1200x400 pixels.', upload_to='carousel_images/', verbose_name='Imagem')),
                ('caption_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título da Legenda')),
                ('caption_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto da Legenda')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de aparição (números menores primeiro).')),
            ],
            options={
                'verbose_name': 'Imagem do Carrossel',
                'verbose_name_plural': 'Imagens do Carrossel',
                'ordering': ['order'],
            },
        ),
    ]
