# Generated by Django 5.2.6 on 2025-10-20 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_lojafavorita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='favoritada_por',
            field=models.ManyToManyField(blank=True, related_name='lojas_favoritadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lojafavorita',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_relacionados', to='loja.loja'),
        ),
        migrations.AlterField(
            model_name='lojafavorita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_lojas', to=settings.AUTH_USER_MODEL),
        ),
    ]
