# Generated by Django 5.2.6 on 2025-11-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_loja_favoritada_por_alter_lojafavorita_loja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='loja',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
