# Generated by Django 5.2.6 on 2025-10-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_loja_favoritada_por_alter_lojafavorita_loja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
