# Generated by Django 5.2.6 on 2025-10-05 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0002_loja_foto_alter_loja_endereco_alter_loja_telefone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria (ex: Ração, Brinquedos, Higiene)', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição sobre a categoria.', null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.PositiveIntegerField(default=0, help_text='Quantidade em estoque. Para serviços, pode ser 0.')),
                ('disponivel', models.BooleanField(default=True)),
                ('animal_destino', models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato'), ('PASSARO', 'Pássaro'), ('PEIXE', 'Peixe'), ('REPTIL', 'Réptil'), ('ROEDOR', 'Roedor'), ('TODOS', 'Todos')], default='TODOS', max_length=10)),
                ('porte_animal', models.CharField(blank=True, choices=[('PEQUENO', 'Pequeno'), ('MEDIO', 'Médio'), ('GRANDE', 'Grande'), ('TODOS', 'Todos')], default='TODOS', max_length=10)),
                ('idade_animal', models.CharField(blank=True, choices=[('FILHOTE', 'Filhote'), ('ADULTO', 'Adulto'), ('IDOSO', 'Idoso'), ('TODOS', 'Todos')], default='TODOS', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos_fotos/', verbose_name='Foto do Produto')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produto.categoria')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='loja.loja')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
