# Generated by Django 5.2.6 on 2025-10-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='foto',
        ),
        migrations.AddField(
            model_name='produto',
            name='foto_adicional_1',
            field=models.ImageField(blank=True, null=True, upload_to='produtos_fotos/', verbose_name='Foto Adicional 1'),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto_adicional_2',
            field=models.ImageField(blank=True, null=True, upload_to='produtos_fotos/', verbose_name='Foto Adicional 2'),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto_destaque',
            field=models.ImageField(blank=True, null=True, upload_to='produtos_fotos/', verbose_name='Foto de Destaque'),
        ),
    ]
