# Generated by Django 5.2.6 on 2025-10-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_produto_foto_produto_foto_adicional_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='foto_adicional_1',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='foto_adicional_2',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='foto_destaque',
        ),
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos_fotos/', verbose_name='Foto do Produto'),
        ),
    ]
